// Editorial content adapted from the Italian and Spanish Sunnit ecosystem decks (2026).
// Project descriptions are examples from the decks, not measured performance claims.
type Localized = readonly [string, string, string];
const text = (it: string, es: string, en: string): Localized => [it, es, en];
const project = (title: Localized, sector: Localized, description: Localized) => ({ title, sector, description });

const departments = [
  {
    id: 'data', label: text('Data', 'Data', 'Data'), title: text('Data & Analytics', 'Data & Analytics', 'Data & Analytics'),
    headline: text('Dati che sostengono le decisioni.', 'Datos que impulsan decisiones.', 'Data that drives decisions.'),
    description: text('Dalle fonti distribuite a una visione condivisa. Costruiamo architetture dati affidabili, governate e pronte per analytics e AI.', 'De fuentes dispersas a una visión compartida. Construimos arquitecturas de datos fiables, gobernadas y preparadas para analytics e IA.', 'From distributed sources to a shared view. We build reliable, governed data architectures ready for analytics and AI.'),
    skills: text('Lakehouse & Data Warehouse|Pipeline ETL/ELT & DataOps|Governance e qualità del dato|Amministrazione e tuning database', 'Lakehouse & Data Warehouse|Pipelines ETL/ELT & DataOps|Gobierno y calidad del dato|Administración y tuning de bases de datos', 'Lakehouse & Data Warehouse|ETL/ELT pipelines & DataOps|Data governance & quality|Database administration & tuning'),
    projects: [
      project(text('Big Data per istituto bancario', 'Big Data para entidad bancaria', 'Big Data for a bank'), text('Banking', 'Banca', 'Banking'), text('Elaborazione batch e streaming per dati affidabili e reporting regolatorio.', 'Procesamiento batch y streaming para datos fiables y reporting regulatorio.', 'Batch and streaming processing for reliable data and regulatory reporting.')),
      project(text('Data Architect con Databricks', 'Data Architect con Databricks', 'Data architecture with Databricks'), text('Grande distribuzione', 'Gran distribución', 'Retail'), text('Architettura Lakehouse per unificare le fonti di punto vendita, logistica e loyalty.', 'Arquitectura Lakehouse que unifica datos de tiendas, logística y fidelización.', 'A Lakehouse architecture connecting store, logistics and loyalty data.')),
      project(text('Data & AI per magazzino farma', 'Data & IA para almacén farma', 'Data & AI for pharmacy inventory'), text('Farma · Salute', 'Farma · Salud', 'Pharma · Health'), text('Pipeline e modelli predittivi per la gestione delle scorte e del riordino.', 'Pipelines y modelos predictivos para gestionar inventario y reposición.', 'Pipelines and predictive models for inventory management and replenishment.')),
      project(text('DBA per il settore assicurativo', 'DBA para el sector asegurador', 'Database administration for insurance'), text('Assicurazioni', 'Seguros', 'Insurance'), text('Amministrazione, ottimizzazione e alta disponibilità di database critici.', 'Administración, optimización y alta disponibilidad de bases de datos críticas.', 'Administration, optimization and high availability for critical databases.')),
    ],
  },
  {
    id: 'ai', label: text('AI', 'IA', 'AI'), title: text('AI & GenAI', 'IA & GenAI', 'AI & GenAI'),
    headline: text('AI integrata nel business.', 'IA integrada en el negocio.', 'AI connected to your business.'),
    description: text('Connettiamo modelli, dati e processi per portare l’intelligenza artificiale nei flussi di lavoro quotidiani.', 'Conectamos modelos, datos y procesos para integrar la inteligencia artificial en el trabajo diario.', 'We connect models, data and processes to bring artificial intelligence into everyday workflows.'),
    skills: text('Sistemi multi-agente & GenAI|Modelli predittivi & MLOps|NLP, chatbot e assistenti|AI integrata in CRM e piattaforme', 'Sistemas multiagente & GenAI|Modelos predictivos & MLOps|NLP, chatbots y asistentes|IA integrada en CRM y plataformas', 'Multi-agent systems & GenAI|Predictive models & MLOps|NLP, chatbots & assistants|AI integrated into CRM & platforms'),
    projects: [
      project(text('Sistema multi-agente multi-DB', 'Sistema multiagente y multi-database', 'Multi-agent, multi-database system'), text('Assicurazioni', 'Seguros', 'Insurance'), text('Agenti AI che interrogano e orchestrano più database in linguaggio naturale.', 'Agentes de IA que consultan y orquestan varias bases de datos en lenguaje natural.', 'AI agents that query and orchestrate multiple databases using natural language.')),
      project(text('AI con Salesforce e integrazioni', 'IA con Salesforce e integraciones', 'AI with Salesforce integrations'), text('Multisettore · CRM', 'Multisector · CRM', 'Cross-industry · CRM'), text('Capacità AI connesse ai sistemi del cliente per vendite e assistenza.', 'Capacidades de IA conectadas a los sistemas del cliente para ventas y servicio.', 'AI capabilities connected to client systems for sales and customer service.')),
      project(text('AI per piattaforme gaming', 'IA para plataformas gaming', 'AI for gaming platforms'), text('Gaming', 'Gaming', 'Gaming'), text('Funzionalità AI per personalizzare l’esperienza sulle piattaforme di gioco online.', 'Funciones de IA para personalizar la experiencia en plataformas de juego online.', 'AI features that personalize the experience on online gaming platforms.')),
    ],
  },
  {
    id: 'developing', label: text('Developing', 'Developing', 'Developing'), title: text('Software & Backend', 'Software & Backend', 'Software & Backend'),
    headline: text('Backend robusto e scalabile.', 'Backend robusto y escalable.', 'Robust, scalable backend systems.'),
    description: text('Progettiamo il motore delle piattaforme digitali: servizi, integrazioni e software capaci di crescere con il business.', 'Diseñamos el motor de las plataformas digitales: servicios, integraciones y software que crecen con el negocio.', 'We engineer the foundations of digital platforms: services, integrations and software that grow with your business.'),
    skills: text('Java, .NET e microservizi|API e integrazioni|Alta disponibilità e performance|Modernizzazione sistemi legacy', 'Java, .NET y microservicios|APIs e integraciones|Alta disponibilidad y rendimiento|Modernización de sistemas legacy', 'Java, .NET & microservices|APIs & integrations|High availability & performance|Legacy modernization'),
    projects: [
      project(text('Backend Java per fatturazione', 'Backend Java para facturación', 'Java backend for invoicing'), text('Fatturazione elettronica', 'Facturación electrónica', 'Electronic invoicing'), text('Servizi backend per piattaforme di e-invoicing con alti volumi e requisiti fiscali.', 'Servicios backend de e-invoicing para altos volúmenes y requisitos fiscales.', 'Backend services for high-volume e-invoicing platforms with tax requirements.')),
      project(text('Backend per software logistico', 'Backend para software logístico', 'Backend for logistics software'), text('Logistica', 'Logística', 'Logistics'), text('Servizi e API per integrare in tempo reale i flussi di una piattaforma logistica.', 'Servicios y APIs que integran flujos en tiempo real en una plataforma logística.', 'Services and APIs integrating real-time flows in a logistics platform.')),
      project(text('Sviluppo .NET per polizze', 'Desarrollo .NET para pólizas', '.NET development for insurance policies'), text('Assicurazioni', 'Seguros', 'Insurance'), text('Applicazione .NET per digitalizzare il ciclo di sottoscrizione delle polizze.', 'Aplicación .NET para digitalizar el ciclo de suscripción de pólizas.', 'A .NET application to digitize the insurance policy underwriting cycle.')),
    ],
  },
  {
    id: 'apps', label: text('Apps', 'Apps', 'Apps'), title: text('Front-end, Mobile & Gaming', 'Front-end, Mobile & Gaming', 'Front-end, Mobile & Gaming'),
    headline: text('Esperienze digitali ad alto impatto.', 'Experiencias digitales de alto impacto.', 'Digital experiences with impact.'),
    description: text('Dall’interfaccia web all’app mobile, mettiamo al centro l’esperienza delle persone e la qualità di ogni interazione.', 'De la interfaz web a la app móvil, ponemos la experiencia de las personas y la calidad de cada interacción en el centro.', 'From web interfaces to mobile apps, we focus on people and the quality of every interaction.'),
    skills: text('Front-end web, SPA & PWA|App mobile native e ibride|UX/UI & design system|Gamification & engagement', 'Front-end web, SPA & PWA|Apps móviles nativas e híbridas|UX/UI & design systems|Gamification & engagement', 'Web front-end, SPA & PWA|Native & hybrid mobile apps|UX/UI & design systems|Gamification & engagement'),
    projects: [
      project(text('Front-end dell’area account', 'Front-end del área de cuenta', 'Account area front-end'), text('Gambling', 'Gambling', 'Gambling'), text('Registrazione, profilo e gestione account del giocatore con requisiti di sicurezza e compliance.', 'Registro, perfil y gestión de cuenta del jugador con requisitos de seguridad y compliance.', 'Player registration, profiles and account management with security and compliance requirements.')),
      project(text('Piattaforme di gamification', 'Plataformas de gamification', 'Gamification platforms'), text('Gaming · Corporate', 'Gaming · Corporativo', 'Gaming · Corporate'), text('Piattaforme per motivare i team attraverso sfide e premi.', 'Plataformas para motivar a los equipos mediante retos y recompensas.', 'Platforms that motivate teams through challenges and rewards.')),
      project(text('App e mobile development', 'Apps y mobile development', 'Apps & mobile development'), text('Banking · Gambling · Energia', 'Banca · Gambling · Energía', 'Banking · Gambling · Energy'), text('App mobile per tre settori regolamentati, con attenzione a performance e sicurezza.', 'Apps móviles para tres sectores regulados, con foco en rendimiento y seguridad.', 'Mobile apps for three regulated industries, focused on performance and security.')),
    ],
  },
  {
    id: 'qa', label: text('QA', 'QA', 'QA'), title: text('QA & Testing', 'QA & Testing', 'QA & Testing'),
    headline: text('Qualità che si automatizza.', 'Calidad que se automatiza.', 'Quality built into every release.'),
    description: text('Affianchiamo lo sviluppo con test funzionali, automazione e verifiche di carico, per rendere ogni rilascio più affidabile.', 'Acompañamos el desarrollo con pruebas funcionales, automatización y pruebas de carga para entregas más fiables.', 'We support development with functional testing, automation and load testing for more reliable releases.'),
    skills: text('Testing funzionale e regressione|Automazione E2E|Test di carico e performance|QA integrato in CI/CD', 'Testing funcional y regresión|Automatización E2E|Pruebas de carga y rendimiento|QA integrado en CI/CD', 'Functional & regression testing|E2E automation|Load & performance testing|QA integrated into CI/CD'),
    projects: [
      project(text('Software Tester QA', 'Software Tester QA', 'Software QA testing'), text('Gaming', 'Gaming', 'Gaming'), text('Testing funzionale e regressione su piattaforme gaming con cicli di release brevi.', 'Testing funcional y regresión en plataformas gaming con ciclos de release cortos.', 'Functional and regression testing for gaming platforms with short release cycles.')),
      project(text('Automazione test E2E', 'Automatización de pruebas E2E', 'E2E test automation'), text('Retail · E-commerce', 'Retail · E-commerce', 'Retail · E-commerce'), text('Framework di test end-to-end integrato nella pipeline CI/CD.', 'Framework de pruebas end-to-end integrado en el pipeline CI/CD.', 'An end-to-end testing framework integrated into the CI/CD pipeline.')),
      project(text('Test di carico e performance', 'Pruebas de carga y rendimiento', 'Load & performance testing'), text('Banking', 'Banca', 'Banking'), text('Test di carico su pagamenti online per identificare i colli di bottiglia e validare i picchi.', 'Pruebas de carga en pagos online para identificar cuellos de botella y validar picos.', 'Load tests on online payments to identify bottlenecks and validate peak traffic.')),
    ],
  },
  {
    id: 'cloud', label: text('Cloud', 'Cloud', 'Cloud'), title: text('Cloud & DevOps', 'Cloud & DevOps', 'Cloud & DevOps'),
    headline: text('Infrastruttura e delivery continua.', 'Infraestructura y entrega continua.', 'Infrastructure. Continuous delivery.'),
    description: text('Architetture cloud e pipeline automatizzate connettono sviluppo e operations, dalla prima release all’evoluzione della piattaforma.', 'Arquitecturas cloud y pipelines automatizados conectan desarrollo y operaciones, desde la primera release hasta la evolución de la plataforma.', 'Cloud architectures and automated pipelines connect development and operations, from the first release to platform evolution.'),
    skills: text('Azure, AWS & Google Cloud|CI/CD, IaC e container|Osservabilità & SRE|Sicurezza e governance cloud', 'Azure, AWS & Google Cloud|CI/CD, IaC y contenedores|Observabilidad & SRE|Seguridad y gobierno cloud', 'Azure, AWS & Google Cloud|CI/CD, IaC & containers|Observability & SRE|Cloud security & governance'),
    projects: [
      project(text('DevOps in ambito bancario', 'DevOps en ámbito bancario', 'DevOps for banking'), text('Banking', 'Banca', 'Banking'), text('Pipeline CI/CD e automazione dei rilasci per consegne ripetibili e auditabili.', 'Pipelines CI/CD y automatización de despliegues repetibles y auditables.', 'CI/CD pipelines and deployment automation for repeatable, auditable releases.')),
      project(text('DevOps per piattaforme assicurative', 'DevOps para plataformas aseguradoras', 'DevOps for insurance platforms'), text('Assicurazioni', 'Seguros', 'Insurance'), text('Automazione del deploy per ridurre rischi e tempi a ogni release.', 'Automatización del despliegue para reducir riesgos y tiempos en cada release.', 'Deployment automation to reduce risk and time with each release.')),
      project(text('Infrastruttura in ambiente cloud', 'Infraestructura en entorno cloud', 'Cloud infrastructure'), text('Banking', 'Banca', 'Banking'), text('Progettazione di infrastruttura cloud con requisiti di sicurezza e resilienza bancari.', 'Diseño de infraestructura cloud con requisitos de seguridad y resiliencia bancaria.', 'Cloud infrastructure designed for banking security and resilience requirements.')),
    ],
  },
  {
    id: 'networks', label: text('Reti', 'Redes', 'Networks'), title: text('Infrastruttura, Sistemi & Reti', 'Infraestructura, Sistemas & Redes', 'Infrastructure, Systems & Networks'),
    headline: text('Sistemi e reti sempre operativi.', 'Sistemas y redes siempre operativos.', 'Keeping systems and networks running.'),
    description: text('Progettiamo e gestiamo l’infrastruttura che sostiene il lavoro quotidiano: workplace, sistemi, connettività e monitoraggio.', 'Diseñamos y gestionamos la infraestructura del trabajo diario: workplace, sistemas, conectividad y monitorización.', 'We design and manage the infrastructure behind everyday work: workplace, systems, connectivity and monitoring.'),
    skills: text('Microsoft 365 & workplace|Sistemi Windows & Azure AD|Reti, WiFi e comunicazioni|Supporto e monitoraggio', 'Microsoft 365 & workplace|Sistemas Windows & Azure AD|Redes, WiFi y comunicaciones|Soporte y monitorización', 'Microsoft 365 & workplace|Windows systems & Azure AD|Networks, WiFi & communications|Support & monitoring'),
    projects: [
      project(text('Architetto Workplace 365', 'Arquitecto Workplace 365', 'Workplace 365 architecture'), text('Multisettore', 'Multisector', 'Cross-industry'), text('Ambiente di lavoro digitale Microsoft 365 per collaborazione, sicurezza e identità.', 'Entorno de trabajo digital Microsoft 365 para colaboración, seguridad e identidad.', 'A Microsoft 365 digital workplace for collaboration, security and identity.')),
      project(text('Sistemista Microsoft', 'Sistemista Microsoft', 'Microsoft systems administration'), text('Assicurazioni', 'Seguros', 'Insurance'), text('Amministrazione di server, directory e ambienti Microsoft per sistemi critici.', 'Administración de servidores, directorio y entornos Microsoft para sistemas críticos.', 'Server, directory and Microsoft environment administration for critical systems.')),
      project(text('Sistemista di reti', 'Sistemista de redes', 'Network administration'), text('Hospitality', 'Hotelero', 'Hospitality'), text('Progettazione, gestione e manutenzione delle reti di strutture alberghiere.', 'Diseño, gestión y mantenimiento de redes de establecimientos hoteleros.', 'Design, management and maintenance of hotel networks.')),
    ],
  },
  {
    id: 'security', label: text('Security', 'Security', 'Security'), title: text('Cybersecurity', 'Ciberseguridad', 'Cybersecurity'),
    headline: text('Sicurezza integrata in ogni livello.', 'Seguridad integrada en cada capa.', 'Security at every layer.'),
    description: text('Dalla prevenzione alla risposta, proteggiamo applicazioni, infrastrutture e dati con un approccio integrato al rischio.', 'De la prevención a la respuesta, protegemos aplicaciones, infraestructura y datos con un enfoque integrado del riesgo.', 'From prevention to response, we protect applications, infrastructure and data with an integrated approach to risk.'),
    skills: text('Pentesting & red teaming|Vulnerabilità e hardening|SIEM, SOC & incident response|ISO 27001, NIS2 & ENS', 'Pentesting & red teaming|Vulnerabilidades y hardening|SIEM, SOC & respuesta a incidentes|ISO 27001, NIS2 & ENS', 'Pentesting & red teaming|Vulnerabilities & hardening|SIEM, SOC & incident response|ISO 27001, NIS2 & ENS'),
    projects: [
      project(text('Pentesting in cybersecurity', 'Pentesting en ciberseguridad', 'Cybersecurity penetration testing'), text('Aziende', 'Empresas', 'Enterprise'), text('Test di intrusione su applicazioni e infrastrutture con priorità di remediation.', 'Pruebas de intrusión en aplicaciones e infraestructuras con prioridades de remediación.', 'Penetration testing on applications and infrastructure with remediation priorities.')),
      project(text('Hardening e vulnerabilità', 'Hardening y vulnerabilidades', 'Hardening & vulnerabilities'), text('Energia', 'Energía', 'Energy'), text('Hardening di server e rete aziendale con revisione delle configurazioni.', 'Bastionado de servidores y red corporativa con revisión de configuración.', 'Server and corporate network hardening with configuration reviews.')),
      project(text('Implementazione SIEM', 'Implantación de SIEM', 'SIEM implementation'), text('Banking · Fintech', 'Banca · Fintech', 'Banking · Fintech'), text('Deploy di SIEM con use case, alert e dashboard per la rilevazione delle minacce.', 'Despliegue de SIEM con casos de uso, alertas y dashboards de detección.', 'SIEM deployment with use cases, alerts and threat detection dashboards.')),
    ],
  },
  {
    id: 'business', label: text('Business', 'Business', 'Business'), title: text('Enterprise Platforms & Digital Business', 'Enterprise Platforms & Digital Business', 'Enterprise Platforms & Digital Business'),
    headline: text('Piattaforme che uniscono business e cliente.', 'Plataformas que conectan negocio y cliente.', 'Platforms connecting business and customers.'),
    description: text('Uniamo CRM, processi e canali digitali per una visione condivisa del cliente e un business più connesso.', 'Unimos CRM, procesos y canales digitales para una visión compartida del cliente y un negocio más conectado.', 'We bring together CRM, processes and digital channels for a shared customer view and a more connected business.'),
    skills: text('Dynamics 365 & Salesforce|Integrazioni ERP e terze parti|Automazione dei processi|Digital marketing & advertising', 'Dynamics 365 & Salesforce|Integraciones ERP y terceros|Automatización de procesos|Marketing digital & advertising', 'Dynamics 365 & Salesforce|ERP & third-party integrations|Process automation|Digital marketing & advertising'),
    projects: [
      project(text('Sviluppo e gestione CRM Dynamics', 'Desarrollo y gestión de CRM Dynamics', 'Dynamics CRM development & management'), text('Multisettore', 'Multisector', 'Cross-industry'), text('Implementazione, personalizzazione ed evoluzione di Dynamics per processi e reporting centralizzati.', 'Implantación, personalización y evolución de Dynamics para procesos y reporting centralizados.', 'Dynamics implementation, customization and evolution for centralized processes and reporting.')),
      project(text('Gestione e sviluppo Salesforce', 'Gestión y desarrollo Salesforce', 'Salesforce management & development'), text('Multisettore', 'Multisector', 'Cross-industry'), text('Sviluppo, amministrazione e integrazioni Salesforce per processi in evoluzione.', 'Desarrollo, administración e integraciones de Salesforce para procesos cambiantes.', 'Salesforce development, administration and integrations for evolving processes.')),
      project(text('Marketing e advertising', 'Marketing y advertising', 'Marketing & advertising'), text('Digital trust', 'Digital trust', 'Digital trust'), text('Gestione di campagne e strategia digitale per una società di digital trust.', 'Gestión de campañas y estrategia digital para una sociedad de digital trust.', 'Campaign management and digital strategy for a digital trust company.')),
    ],
  },
];

const copy = {
  it: { back: 'Torna all’ecosistema', close: 'Chiudi dettagli', projectDetails: 'Scopri il progetto', projectLabel: 'Progetto', relatedSkills: 'Competenze dell’ambito', scopeHint: 'Seleziona un progetto per i dettagli. Riclicca il nodo per tornare.', nav: 'Ecosistema', eyebrow: 'L’ECOSISTEMA SUNNIT', title: 'Competenze diverse.', accent: 'Un’unica direzione.', intro: 'Nove team verticali, connessi sotto un unico interlocutore. Esplora le competenze che danno forma al tuo prossimo progetto.', explore: 'Seleziona una bolla e scopri cosa possiamo costruire insieme.', map: 'Mappa interattiva delle competenze Sunnit', team: 'Competenze', projects: 'Progetti in evidenza', partner: 'Un unico interlocutore', selected: 'Stai esplorando', skills: 'Cosa sviluppiamo', examples: 'Dalle competenze ai progetti.', examplesIntro: 'Una selezione di esperienze nei settori in cui lavoriamo.', contact: 'Parliamo del tuo progetto', all: 'Esplora l’ecosistema', pause: 'Pausa animazioni', play: 'Attiva animazioni', next: 'Competenza successiva', previous: 'Competenza precedente', ctaTitle: 'Il tuo prossimo progetto,\nle competenze giuste.', ctaText: 'Connettiamo le persone e le tecnologie di cui hai bisogno, dal primo confronto alla delivery.', meta: 'Esplora le nove competenze Sunnit: Data, AI, sviluppo, app, QA, cloud, reti, cybersecurity e business. Team connessi, progetti reali.' },
  es: { back: 'Volver al ecosistema', close: 'Cerrar detalles', projectDetails: 'Explora el proyecto', projectLabel: 'Proyecto', relatedSkills: 'Competencias del ámbito', scopeHint: 'Selecciona un proyecto para ver los detalles. Pulsa el nodo para volver.', nav: 'Ecosistema', eyebrow: 'EL ECOSISTEMA SUNNIT', title: 'Competencias distintas.', accent: 'Una misma dirección.', intro: 'Nueve equipos especializados, conectados con un único interlocutor. Explora las competencias que dan forma a tu próximo proyecto.', explore: 'Selecciona una burbuja y descubre qué podemos construir juntos.', map: 'Mapa interactivo de competencias Sunnit', team: 'Competencias', projects: 'Proyectos destacados', partner: 'Un único interlocutor', selected: 'Estás explorando', skills: 'Qué desarrollamos', examples: 'De las competencias a los proyectos.', examplesIntro: 'Una selección de experiencias en los sectores donde trabajamos.', contact: 'Hablemos de tu proyecto', all: 'Explora el ecosistema', pause: 'Pausar animaciones', play: 'Activar animaciones', next: 'Siguiente competencia', previous: 'Competencia anterior', ctaTitle: 'Tu próximo proyecto,\nlas competencias adecuadas.', ctaText: 'Conectamos las personas y las tecnologías que necesitas, desde la primera conversación hasta la entrega.', meta: 'Explora las nueve competencias Sunnit: Data, IA, desarrollo, apps, QA, cloud, redes, ciberseguridad y negocio. Equipos conectados y proyectos reales.' },
  en: { back: 'Back to the ecosystem', close: 'Close details', projectDetails: 'Explore the project', projectLabel: 'Project', relatedSkills: 'Expertise in this area', scopeHint: 'Select a project for details. Click the parent node again to return.', nav: 'Ecosystem', eyebrow: 'THE SUNNIT ECOSYSTEM', title: 'Different expertise.', accent: 'One shared direction.', intro: 'Nine specialist teams, connected through a single partner. Explore the expertise that shapes your next project.', explore: 'Select a bubble and discover what we can build together.', map: 'Interactive map of Sunnit expertise', team: 'Specialist teams', projects: 'Featured projects', partner: 'One connected partner', selected: 'You’re exploring', skills: 'What we build', examples: 'From expertise to projects.', examplesIntro: 'A selection of experience across the industries we work in.', contact: 'Let’s talk about your project', all: 'Explore the ecosystem', pause: 'Pause animations', play: 'Enable animations', next: 'Next team', previous: 'Previous team', ctaTitle: 'Your next project,\nthe right expertise.', ctaText: 'We connect the people and technology you need, from the first conversation to delivery.', meta: 'Explore nine Sunnit specialisms: Data, AI, development, apps, QA, cloud, networks, cybersecurity and business. Connected teams and real projects.' },
};

export function getEcosystemContent(lang: string) {
  const locale = lang === 'es' || lang === 'en' ? lang : 'it';
  const index = locale === 'it' ? 0 : locale === 'es' ? 1 : 2;
  const localize = (value: Localized) => value[index];
  return {
    copy: copy[locale],
    departments: departments.map(d => ({
      id: d.id, label: localize(d.label), title: localize(d.title), headline: localize(d.headline), description: localize(d.description),
      skills: localize(d.skills).split('|'),
      projects: d.projects.map(p => ({ title: localize(p.title), sector: localize(p.sector), description: localize(p.description) })),
    })),
  };
}
export type EcosystemContent = ReturnType<typeof getEcosystemContent>;
